"""Add API polling fields to Workspace

Revision ID: 15a1ebc87902
Revises: 300746d0e618
Create Date: 2025-09-28 12:55:03.764982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15a1ebc87902'
down_revision: Union[str, Sequence[str], None] = '300746d0e618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('api_url', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('polling_interval', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'polling_interval')
    op.drop_column('workspaces', 'api_url')
    # ### end Alembic commands ###
