"""Add ai_insight to notifications

Revision ID: 3e2a37d9b119
Revises: ef0f48e53fd3
Create Date: 2025-10-02 13:02:59.597802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e2a37d9b119'
down_revision: Union[str, Sequence[str], None] = 'ef0f48e53fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('ai_insight', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'ai_insight')
    # ### end Alembic commands ###
