"""Add last_polled_at to Workspace

Revision ID: 41aadd9180e1
Revises: 15a1ebc87902
Create Date: 2025-09-28 13:35:25.069190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41aadd9180e1'
down_revision: Union[str, Sequence[str], None] = '15a1ebc87902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('last_polled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'last_polled_at')
    # ### end Alembic commands ###
