"""Add is_polling_active to Workspace model

Revision ID: 56e7f9cb1f53
Revises: a72661ff8cda
Create Date: 2025-09-28 17:32:35.494724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e7f9cb1f53'
down_revision: Union[str, Sequence[str], None] = 'a72661ff8cda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('is_polling_active', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'is_polling_active')
    # ### end Alembic commands ###
