"""Add file_content to data_uploads

Revision ID: 61a0e95d20c6
Revises: 2ccdab7470e0
Create Date: 2025-10-13 14:27:13.570835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61a0e95d20c6'
down_revision: Union[str, Sequence[str], None] = '2ccdab7470e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
