"""Add tracked_column to Workspace

Revision ID: 64f8d9c33b0a
Revises: 864e47dcb62c
Create Date: 2025-09-29 16:08:49.282339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64f8d9c33b0a'
down_revision: Union[str, Sequence[str], None] = '864e47dcb62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('tracked_column', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'tracked_column')
    # ### end Alembic commands ###
