"""Add file_content to data_uploads

Revision ID: 6beb927cd557
Revises: 61a0e95d20c6
Create Date: 2025-10-13 14:35:47.464461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6beb927cd557'
down_revision: Union[str, Sequence[str], None] = '61a0e95d20c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_uploads', sa.Column('file_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_uploads', 'file_content')
    # ### end Alembic commands ###
