"""Add database connector fields to workspace

Revision ID: 9f664b0fc8ba
Revises: c630d83ba9d0
Create Date: 2025-10-11 13:41:06.917571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from app.models.workspace import EncryptedString

# revision identifiers, used by Alembic.
revision: str = '9f664b0fc8ba'
down_revision: Union[str, Sequence[str], None] = 'c630d83ba9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    op.add_column('workspaces', sa.Column('db_type', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('db_host', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('db_port', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('db_user', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('db_password', EncryptedString(), nullable=True))
    op.add_column('workspaces', sa.Column('db_name', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('db_query', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'db_query')
    op.drop_column('workspaces', 'db_name')
    op.drop_column('workspaces', 'db_password')
    op.drop_column('workspaces', 'db_user')
    op.drop_column('workspaces', 'db_port')
    op.drop_column('workspaces', 'db_host')
    op.drop_column('workspaces', 'db_type')
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('invitations_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitations_pkey')),
    sa.UniqueConstraint('token', name=op.f('invitations_token_key'))
    )
    # ### end Alembic commands ###
