"""Add upload_type to DataUpload model

Revision ID: a72661ff8cda
Revises: 47b5113660b1
Create Date: 2025-09-28 16:04:12.547773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a72661ff8cda'
down_revision: Union[str, Sequence[str], None] = '47b5113660b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_uploads', sa.Column('upload_type', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_uploads', 'upload_type')
    # ### end Alembic commands ###
