"""Add description timestamp to workspace

Revision ID: a926d2d61d00
Revises: 9f664b0fc8ba
Create Date: 2025-10-11 17:34:00.889088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a926d2d61d00'
down_revision: Union[str, Sequence[str], None] = '9f664b0fc8ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('description_last_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'description_last_updated_at')
    # ### end Alembic commands ###
